### ISSUE TITLE
Errors in npm test

### ISSUE THREAD

**Issue by Pierre-RA** [anthillsolutions/nutrient#10]
We should correct those bugs before we get non zero exit status.

```
  1) API tests - index "before all" hook:
     MongoError: failed to connect to server [undefined:27017] on first connect
at Pool.<anonymous> (node_modules/mongodb-core/lib/topologies/server.js:326:35)
at Connection.<anonymous> (node_modules/mongodb-core/lib/connection/pool.js:270:12)
at Socket.<anonymous> (node_modules/mongodb-core/lib/connection/connection.js:175:49)
at connectErrorNT (net.js:1025:8)
at _combinedTickCallback (internal/process/next_tick.js:74:11)
at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  2) API tests - users should return 200 for /users:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.


  3) API tests - users should add/get/update/delete a user:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.




Unhandled rejection Error in plugin 'gulp-mocha'
Message:
3 tests failed.

(node:6258) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'header' of undefined
(node:6258) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Pierre-RA** [comment]
Corrected in Codeship.
